#!/bin/sh
BRANCH=$(git status | head -n 1 | tr ' ' '\n' | tail -n 1 | grep -o '[A-Z]\+-[0-9]\+')
if [ ! -z "$BRANCH" ];then
if [ "$1" == "start" ] ||
[ "$1" == "stop" ] ||
[ "$1" == "log" ] ||
[ "$1" == "resolve" ] ||
[ "$1" == "reopen" ] ||
[ "$1" == "close" ] ||
[ "$1" == "needinfo" ] ||
[ "$1" == "describe" ] ||
[ "$1" == "comments" ] ||
[ "$1" == "subtasks" ] ||
[ "$1" == "status" ] ||
[ "$1" == "comment" ] ||
[ "$1" == "assign" ];then
  ARGS="$1 $BRANCH"
  shift
  ARGS="$ARGS $@"
  jilla $ARGS
else
  jilla $@
fi
else
  jilla $@
fi